{{- if .Values.ovh.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-mks-exporter.fullname" . }}
  labels:
    {{- include "ovh-mks-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OVH_ENDPOINT: {{ .Values.ovh.endpoint }}
  OVH_APPLICATION_KEY: {{ .Values.ovh.applicationKey }}
  OVH_APPLICATION_SECRET: {{ .Values.ovh.applicationSecret }}
  OVH_CONSUMER_KEY: {{ .Values.ovh.consumerKey }}
  OVH_CLOUD_PROJECT_SERVICE: {{ .Values.ovh.cloudProjectServiceName }}
{{- end }}